### ISSUE TITLE
[Question] Defining "test_labels" and "target_class" for custom dataset.json

### ISSUE THREAD

**Issue by salusanga** [MIC-DKFZ/nnDetection#233] opened 2024-03-05 12:56 UTC
Hi,
I have a custom dataset for brain metastasis detection. It is a binary task, in the original dataset "1" is the FG and "0" is BG.
I brought it to the nnDetection format, with the instances in the masks and the new FG class being "0".

In this context, how should I set "test_labels" and "target_class" in dataset.json? 

Thanks a lot!
Best,
Sara

**Comment by mibaumgartner** [comment] 2024-03-20 13:23
Duplicate of #232

**Closed by mibaumgartner** 2024-03-20 13:23 UTC
