### ISSUE TITLE
[Bug] nndet_prep fails in instance.py with KeyError 'instances'

### ISSUE THREAD

**Issue by xaratustrah** [MIC-DKFZ/nnDetection#118] opened 2022-11-23 09:03 UTC
### :skull: Bug

running `nndet_prep 000` on example data set, that was created by `nndet_example`: Processing fails after several successful iterations with *case_9* suddenly with the following error message. This also happens with **my own data set**.

```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/USERNAME/miniconda3/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/USERNAME/miniconda3/lib/python3.9/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/USERNAME/git/nnDetection/nndet/planning/properties/instance.py", line 155, in analyze_instances_per_case
    props["num_instances"] = count_instances(props, all_classes)
  File "/home/USERNAME/git/nnDetection/nndet/planning/properties/instance.py", line 176, in count_instances
    instance_classes = list(map(int, props["instances"].values()))
KeyError: 'instances'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/USERNAME/miniconda3/bin/nndet_prep", line 33, in <module>
    sys.exit(load_entry_point('nndet', 'console_scripts', 'nndet_prep')())
  File "/home/USERNAME/git/nnDetection/nndet/utils/check.py", line 58, in wrapper
    return func(*args, **kwargs)
  File "/home/USERNAME/git/nnDetection/scripts/preprocess.py", line 406, in main
    run(OmegaConf.to_container(cfg, resolve=True),
  File "/home/USERNAME/git/nnDetection/scripts/preprocess.py", line 325, in run
    run_dataset_analysis(cropped_output_dir=Path(cfg["host"]["cropped_output_dir"]),
  File "/home/USERNAME/git/nnDetection/scripts/preprocess.py", line 129, in run_dataset_analysis
    _ = analyzer.analyze_dataset(properties)
  File "/home/USERNAME/git/nnDetection/nndet/planning/analyzer.py", line 80, in analyze_dataset
    props.update(property_fn(self))
  File "/home/USERNAME/git/nnDetection/nndet/planning/properties/instance.py", line 46, in analyze_instances
    props_per_case = run_analyze_instances(analyzer, all_classes)
  File "/home/USERNAME/git/nnDetection/nndet/planning/properties/instance.py", line 77, in run_analyze_instances
    props = p.starmap(analyze_instances_per_case, zip(
  File "/home/USERNAME/miniconda3/lib/python3.9/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/home/USERNAME/miniconda3/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
KeyError: 'instances'
```

### Environment
Please provide some information about the used environment.

```
----- PyTorch Information -----
PyTorch Version: 1.13.0
PyTorch Debug: False
PyTorch CUDA: 11.7
PyTorch Backend cudnn: 8500
PyTorch CUDA Arch List: ['sm_37', 'sm_50', 'sm_60', 'sm_61', 'sm_70', 'sm_75', 'sm_80', 'sm_86', 'compute_37']
PyTorch Current Device Capability: (3, 7)
PyTorch CUDA available: True


----- System Information -----
System NVCC: nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Jun__8_16:49:14_PDT_2022
Cuda compilation tools, release 11.7, V11.7.99
Build cuda_11.7.r11.7/compiler.31442593_0

System Arch List: None
System OMP_NUM_THREADS: 1
System CUDA_HOME is None: True
System CPU Count: 12
Python Version: 3.9.15 (main, Nov  4 2022, 16:13:54) 
[GCC 11.2.0]


----- nnDetection Information -----
det_num_threads 12
det_data is set True
det_models is set True
```

How was nnDetection installed [`docker` | `source`]:

```
source
```

Environment Information:
```text
GPU: Tesla K80
Nvidia driver 470
CUDA 11.7
CUDNN 8.6
PyTorch 1.13
Python 3.9.15
```

If necessary, please provide the used run command with all overwrites:
```text
nndet_prep 000
```

**Comment by mibaumgartner** [comment] 2022-11-23 09:45
Indeed, that is not the expected behaviour. I just reran the example from the github main branch without problems though... 

The commands I ran:
```
nndet_example
nndet_prep 000D3
```

The error indicates that one of the json files from the labels doesn't contain the "instances" key. Could you manually check that all of them are available? (Since the example is small, this shouldn't take a long time)
Also make sure to delete previous cropped and preprocessed folders in order to avoid any problems from past versions.

**Comment by mibaumgartner** [comment] 2022-11-24 10:08
I used `000D3` because I have another `000D3XX` dataset to play around with, there is no functional difference. 

When using the default values of nndet_prep, please make sure that there is enough RAM available (this is a very unlikely cause, but it is still better to exclude this). 

----

Please make sure to pull the master before running this, since I updated the scripts to support num processes 0 (which is a version without multiprocessing) and merged some of the project branches with minor bug fixes.

It is really strange that it doesn't work, just tested it locally again (with the original and new main branch) without errors. Can you try to run

`nndet_prep 000 -np 0 -npp 0`

which will disable the multiprocessing. Sometimes multiprocessing hides some other problem.

**Comment by xaratustrah** [comment] 2022-11-24 10:32
thanks for coming back to this issue. I have 512 GB of RAM on that GPU node. (Would it be nice if `nndet_env` would also include CPU, RAM and GPU information?)

After updating and running:
```
git pull && pip install -e .
```
then:
```
 cd $det_data && rm -rf * && nndet_example && nndet_prep 000
```
causes the same errors as before. running:

```
rm -rf * && nndet_example && nndet_prep 000 -np 0 -npp 0
```
causes a new error in a later stage which is similar to the other one:

```
'det_verbose' environment variable not set. Continue in verbose mode.
2022-11-24 11:22:56.790 | INFO     | scripts.generate_example:generate_image:53 - Generating case_0
2022-11-24 11:23:03.826 | INFO     | scripts.generate_example:generate_image:53 - Generating case_1
2022-11-24 11:23:10.666 | INFO     | scripts.generate_example:generate_image:53 - Generating case_2
2022-11-24 11:23:17.494 | INFO     | scripts.generate_example:generate_image:53 - Generating case_3
2022-11-24 11:23:24.415 | INFO     | scripts.generate_example:generate_image:53 - Generating case_4
2022-11-24 11:23:31.340 | INFO     | scripts.generate_example:generate_image:53 - Generating case_5
2022-11-24 11:23:38.241 | INFO     | scripts.generate_example:generate_image:53 - Generating case_6
2022-11-24 11:23:45.062 | INFO     | scripts.generate_example:generate_image:53 - Generating case_7
2022-11-24 11:23:51.961 | INFO     | scripts.generate_example:generate_image:53 - Generating case_8
2022-11-24 11:23:58.881 | INFO     | scripts.generate_example:generate_image:53 - Generating case_9
2022-11-24 11:24:05.780 | INFO     | scripts.generate_example:generate_image:53 - Generating case_10
2022-11-24 11:24:12.581 | INFO     | scripts.generate_example:generate_image:53 - Generating case_11
2022-11-24 11:24:19.386 | INFO     | scripts.generate_example:generate_image:53 - Generating case_12
2022-11-24 11:24:26.188 | INFO     | scripts.generate_example:generate_image:53 - Generating case_13
2022-11-24 11:24:33.088 | INFO     | scripts.generate_example:generate_image:53 - Generating case_14
2022-11-24 11:24:39.996 | INFO     | scripts.generate_example:generate_image:53 - Generating case_15
2022-11-24 11:24:46.802 | INFO     | scripts.generate_example:generate_image:53 - Generating case_16
2022-11-24 11:24:53.716 | INFO     | scripts.generate_example:generate_image:53 - Generating case_17
2022-11-24 11:25:00.545 | INFO     | scripts.generate_example:generate_image:53 - Generating case_18
2022-11-24 11:25:07.346 | INFO     | scripts.generate_example:generate_image:53 - Generating case_19
'det_verbose' environment variable not set. Continue in verbose mode.
/home/gpuadmin/git/nnDetection/scripts/preprocess.py:381: UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  initialize_config_module(config_module="nndet.conf")
Start dataset info check.
Dataset info check complete.
Start data and label check: test=False
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 10257.53it/s]
Data and label check complete.
Start data and label check: test=True
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 10559.68it/s]
Data and label check complete.
2022-11-24 11:25:18.194 | INFO     | scripts.preprocess:run_cropping_and_convert:75 - Running cropping with overwrite False.
2022-11-24 11:25:18.197 | INFO     | nndet.preprocessing.crop:process_data:223 - Processing case case_0
2022-11-24 11:25:20.428 | INFO     | nndet.preprocessing.crop:crop:288 - Shape before crop (1, 256, 256, 256); after crop (1, 256, 256, 256); spacing [1. 1. 1.]
2022-11-24 11:25:23.818 | INFO     | nndet.preprocessing.crop:process_data:223 - Processing case case_1
2022-11-24 11:25:26.021 | INFO     | nndet.preprocessing.crop:crop:288 - Shape before crop (1, 256, 256, 256); after crop (1, 256, 256, 256); spacing [1. 1. 1.]
2022-11-24 11:25:29.379 | INFO     | nndet.preprocessing.crop:process_data:223 - Processing case case_2
2022-11-24 11:25:31.561 | INFO     | nndet.preprocessing.crop:crop:288 - Shape before crop (1, 256, 256, 256); after crop (1, 256, 256, 256); spacing [1. 1. 1.]
2022-11-24 11:25:34.922 | INFO     | nndet.preprocessing.crop:process_data:223 - Processing case case_3
2022-11-24 11:25:37.099 | INFO     | nndet.preprocessing.crop:crop:288 - Shape before crop (1, 256, 256, 256); after crop (1, 256, 256, 256); spacing [1. 1. 1.]
2022-11-24 11:25:40.450 | INFO     | nndet.preprocessing.crop:process_data:223 - Processing case case_4
2022-11-24 11:25:42.626 | INFO     | nndet.preprocessing.crop:crop:288 - Shape before crop (1, 256, 256, 256); after crop (1, 256, 256, 256); spacing [1. 1. 1.]
2022-11-24 11:25:45.979 | INFO     | nndet.preprocessing.crop:process_data:223 - Processing case case_5
2022-11-24 11:25:48.153 | INFO     | nndet.preprocessing.crop:crop:288 - Shape before crop (1, 256, 256, 256); after crop (1, 256, 256, 256); spacing [1. 1. 1.]
2022-11-24 11:25:51.503 | INFO     | nndet.preprocessing.crop:process_data:223 - Processing case case_6
2022-11-24 11:25:53.677 | INFO     | nndet.preprocessing.crop:crop:288 - Shape before crop (1, 256, 256, 256); after crop (1, 256, 256, 256); spacing [1. 1. 1.]
2022-11-24 11:25:57.032 | INFO     | nndet.preprocessing.crop:process_data:223 - Processing case case_7
2022-11-24 11:25:59.204 | INFO     | nndet.preprocessing.crop:crop:288 - Shape before crop (1, 256, 256, 256); after crop (1, 256, 256, 256); spacing [1. 1. 1.]
2022-11-24 11:26:02.556 | INFO     | nndet.preprocessing.crop:process_data:223 - Processing case case_8
2022-11-24 11:26:04.734 | INFO     | nndet.preprocessing.crop:crop:288 - Shape before crop (1, 256, 256, 256); after crop (1, 256, 256, 256); spacing [1. 1. 1.]
2022-11-24 11:26:08.085 | INFO     | nndet.preprocessing.crop:process_data:223 - Processing case case_9
2022-11-24 11:26:10.270 | INFO     | nndet.preprocessing.crop:crop:288 - Shape before crop (1, 256, 256, 256); after crop (1, 256, 256, 256); spacing [1. 1. 1.]
2022-11-24 11:26:13.634 | INFO     | scripts.preprocess:check_case:264 - Checking /data.local.3/shahab/ML/data/Task000D3_Example/raw_cropped/imagesTr/case_0.npz
2022-11-24 11:26:14.102 | INFO     | scripts.preprocess:check_case:264 - Checking /data.local.3/shahab/ML/data/Task000D3_Example/raw_cropped/imagesTr/case_1.npz
2022-11-24 11:26:14.567 | INFO     | scripts.preprocess:check_case:264 - Checking /data.local.3/shahab/ML/data/Task000D3_Example/raw_cropped/imagesTr/case_2.npz
2022-11-24 11:26:15.030 | INFO     | scripts.preprocess:check_case:264 - Checking /data.local.3/shahab/ML/data/Task000D3_Example/raw_cropped/imagesTr/case_3.npz
2022-11-24 11:26:15.495 | INFO     | scripts.preprocess:check_case:264 - Checking /data.local.3/shahab/ML/data/Task000D3_Example/raw_cropped/imagesTr/case_4.npz
2022-11-24 11:26:15.958 | INFO     | scripts.preprocess:check_case:264 - Checking /data.local.3/shahab/ML/data/Task000D3_Example/raw_cropped/imagesTr/case_5.npz
2022-11-24 11:26:16.422 | INFO     | scripts.preprocess:check_case:264 - Checking /data.local.3/shahab/ML/data/Task000D3_Example/raw_cropped/imagesTr/case_6.npz
2022-11-24 11:26:16.886 | INFO     | scripts.preprocess:check_case:264 - Checking /data.local.3/shahab/ML/data/Task000D3_Example/raw_cropped/imagesTr/case_7.npz
2022-11-24 11:26:17.349 | INFO     | scripts.preprocess:check_case:264 - Checking /data.local.3/shahab/ML/data/Task000D3_Example/raw_cropped/imagesTr/case_8.npz
2022-11-24 11:26:17.813 | INFO     | scripts.preprocess:check_case:264 - Checking /data.local.3/shahab/ML/data/Task000D3_Example/raw_cropped/imagesTr/case_9.npz
2022-11-24 11:26:18.276 | INFO     | scripts.preprocess:run_check:242 - Checked 10 cases in /data.local.3/shahab/ML/data/Task000D3_Example/raw_cropped/imagesTr
2022-11-24 11:26:18.276 | INFO     | scripts.preprocess:run_cropping_and_convert:100 - Crop check successful: Loading check completed
2022-11-24 11:26:18.279 | INFO     | nndet.planning.properties.instance:analyze_instances_per_case:157 - Processing instance properties of case case_0
Traceback (most recent call last):
  File "/home/gpuadmin/miniconda3/bin/nndet_prep", line 33, in <module>
    sys.exit(load_entry_point('nndet', 'console_scripts', 'nndet_prep')())
  File "/home/gpuadmin/git/nnDetection/nndet/utils/check.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "/home/gpuadmin/git/nnDetection/scripts/preprocess.py", line 406, in main
    run(OmegaConf.to_container(cfg, resolve=True),
  File "/home/gpuadmin/git/nnDetection/scripts/preprocess.py", line 325, in run
    run_dataset_analysis(cropped_output_dir=Path(cfg["host"]["cropped_output_dir"]),
  File "/home/gpuadmin/git/nnDetection/scripts/preprocess.py", line 129, in run_dataset_analysis
    _ = analyzer.analyze_dataset(properties)
  File "/home/gpuadmin/git/nnDetection/nndet/planning/analyzer.py", line 80, in analyze_dataset
    props.update(property_fn(self))
  File "/home/gpuadmin/git/nnDetection/nndet/planning/properties/instance.py", line 46, in analyze_instances
    props_per_case = run_analyze_instances(analyzer, all_classes)
  File "/home/gpuadmin/git/nnDetection/nndet/planning/properties/instance.py", line 77, in run_analyze_instances
    props = [analyze_instances_per_case(*args) for args in zip(
  File "/home/gpuadmin/git/nnDetection/nndet/planning/properties/instance.py", line 77, in <listcomp>
    props = [analyze_instances_per_case(*args) for args in zip(
  File "/home/gpuadmin/git/nnDetection/nndet/planning/properties/instance.py", line 159, in analyze_instances_per_case
    props["num_instances"] = count_instances(props, all_classes)
  File "/home/gpuadmin/git/nnDetection/nndet/planning/properties/instance.py", line 180, in count_instances
    instance_classes = list(map(int, props["instances"].values()))
KeyError: 'instances'
```

**Comment by mibaumgartner** [comment] 2022-11-24 10:57
Maybe there is something going on with the paths, which OS is running on the GPU node? 
One additional thing to check: can you run the the prepare step with the full check option -> `nndet_prep 000D3 -np 0 -npp 0 --full_check`

**Comment by xaratustrah** [comment] 2022-11-24 13:21
I am running on Ubuntu 20.04 LTS. What do you think about paths? maybe we can explore more on that.

Running:
```
cd $det_data && rm -rf * && nndet_example && nndet_prep 000D3 -np 0 -npp 0 --full_check
```

results in:

```
'det_verbose' environment variable not set. Continue in verbose mode.
2022-11-24 14:14:34.808 | INFO     | scripts.generate_example:generate_image:53 - Generating case_0
2022-11-24 14:14:41.687 | INFO     | scripts.generate_example:generate_image:53 - Generating case_1
2022-11-24 14:14:48.518 | INFO     | scripts.generate_example:generate_image:53 - Generating case_2
2022-11-24 14:14:55.354 | INFO     | scripts.generate_example:generate_image:53 - Generating case_3
2022-11-24 14:15:02.098 | INFO     | scripts.generate_example:generate_image:53 - Generating case_4
2022-11-24 14:15:08.860 | INFO     | scripts.generate_example:generate_image:53 - Generating case_5
2022-11-24 14:15:15.653 | INFO     | scripts.generate_example:generate_image:53 - Generating case_6
2022-11-24 14:15:22.450 | INFO     | scripts.generate_example:generate_image:53 - Generating case_7
2022-11-24 14:15:29.213 | INFO     | scripts.generate_example:generate_image:53 - Generating case_8
2022-11-24 14:15:35.949 | INFO     | scripts.generate_example:generate_image:53 - Generating case_9
2022-11-24 14:15:42.709 | INFO     | scripts.generate_example:generate_image:53 - Generating case_10
2022-11-24 14:15:49.527 | INFO     | scripts.generate_example:generate_image:53 - Generating case_11
2022-11-24 14:15:56.318 | INFO     | scripts.generate_example:generate_image:53 - Generating case_12
2022-11-24 14:16:03.134 | INFO     | scripts.generate_example:generate_image:53 - Generating case_13
2022-11-24 14:16:09.899 | INFO     | scripts.generate_example:generate_image:53 - Generating case_14
2022-11-24 14:16:16.634 | INFO     | scripts.generate_example:generate_image:53 - Generating case_15
2022-11-24 14:16:23.424 | INFO     | scripts.generate_example:generate_image:53 - Generating case_16
2022-11-24 14:16:30.184 | INFO     | scripts.generate_example:generate_image:53 - Generating case_17
2022-11-24 14:16:36.975 | INFO     | scripts.generate_example:generate_image:53 - Generating case_18
2022-11-24 14:16:43.762 | INFO     | scripts.generate_example:generate_image:53 - Generating case_19
'det_verbose' environment variable not set. Continue in verbose mode.
/home/USERNAME/git/nnDetection/scripts/preprocess.py:381: UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  initialize_config_module(config_module="nndet.conf")
Start dataset info check.
Dataset info check complete.
Start data and label check: test=False
100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:16<00:00,  1.68s/it]
Data and label check complete.
Start data and label check: test=True
100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:16<00:00,  1.68s/it]
Data and label check complete.
2022-11-24 14:17:28.017 | INFO     | scripts.preprocess:run_cropping_and_convert:75 - Running cropping with overwrite False.
2022-11-24 14:17:28.020 | INFO     | nndet.preprocessing.crop:process_data:223 - Processing case case_0
2022-11-24 14:17:30.196 | INFO     | nndet.preprocessing.crop:crop:288 - Shape before crop (1, 256, 256, 256); after crop (1, 256, 256, 256); spacing [1. 1. 1.]
2022-11-24 14:17:33.543 | INFO     | nndet.preprocessing.crop:process_data:223 - Processing case case_1
2022-11-24 14:17:35.713 | INFO     | nndet.preprocessing.crop:crop:288 - Shape before crop (1, 256, 256, 256); after crop (1, 256, 256, 256); spacing [1. 1. 1.]
2022-11-24 14:17:39.067 | INFO     | nndet.preprocessing.crop:process_data:223 - Processing case case_2
2022-11-24 14:17:41.287 | INFO     | nndet.preprocessing.crop:crop:288 - Shape before crop (1, 256, 256, 256); after crop (1, 256, 256, 256); spacing [1. 1. 1.]
2022-11-24 14:17:44.686 | INFO     | nndet.preprocessing.crop:process_data:223 - Processing case case_3
2022-11-24 14:17:46.881 | INFO     | nndet.preprocessing.crop:crop:288 - Shape before crop (1, 256, 256, 256); after crop (1, 256, 256, 256); spacing [1. 1. 1.]
2022-11-24 14:17:50.246 | INFO     | nndet.preprocessing.crop:process_data:223 - Processing case case_4
2022-11-24 14:17:52.433 | INFO     | nndet.preprocessing.crop:crop:288 - Shape before crop (1, 256, 256, 256); after crop (1, 256, 256, 256); spacing [1. 1. 1.]
2022-11-24 14:17:55.797 | INFO     | nndet.preprocessing.crop:process_data:223 - Processing case case_5
2022-11-24 14:17:58.021 | INFO     | nndet.preprocessing.crop:crop:288 - Shape before crop (1, 256, 256, 256); after crop (1, 256, 256, 256); spacing [1. 1. 1.]
2022-11-24 14:18:01.387 | INFO     | nndet.preprocessing.crop:process_data:223 - Processing case case_6
2022-11-24 14:18:03.581 | INFO     | nndet.preprocessing.crop:crop:288 - Shape before crop (1, 256, 256, 256); after crop (1, 256, 256, 256); spacing [1. 1. 1.]
2022-11-24 14:18:06.936 | INFO     | nndet.preprocessing.crop:process_data:223 - Processing case case_7
2022-11-24 14:18:09.097 | INFO     | nndet.preprocessing.crop:crop:288 - Shape before crop (1, 256, 256, 256); after crop (1, 256, 256, 256); spacing [1. 1. 1.]
2022-11-24 14:18:12.404 | INFO     | nndet.preprocessing.crop:process_data:223 - Processing case case_8
2022-11-24 14:18:14.560 | INFO     | nndet.preprocessing.crop:crop:288 - Shape before crop (1, 256, 256, 256); after crop (1, 256, 256, 256); spacing [1. 1. 1.]
2022-11-24 14:18:17.857 | INFO     | nndet.preprocessing.crop:process_data:223 - Processing case case_9
2022-11-24 14:18:20.020 | INFO     | nndet.preprocessing.crop:crop:288 - Shape before crop (1, 256, 256, 256); after crop (1, 256, 256, 256); spacing [1. 1. 1.]
2022-11-24 14:18:23.316 | INFO     | scripts.preprocess:check_case:264 - Checking /data.local.3/USERNAME/ML/data/Task000D3_Example/raw_cropped/imagesTr/case_0.npz
2022-11-24 14:18:23.782 | INFO     | scripts.preprocess:check_case:264 - Checking /data.local.3/USERNAME/ML/data/Task000D3_Example/raw_cropped/imagesTr/case_1.npz
2022-11-24 14:18:24.246 | INFO     | scripts.preprocess:check_case:264 - Checking /data.local.3/USERNAME/ML/data/Task000D3_Example/raw_cropped/imagesTr/case_2.npz
2022-11-24 14:18:24.709 | INFO     | scripts.preprocess:check_case:264 - Checking /data.local.3/USERNAME/ML/data/Task000D3_Example/raw_cropped/imagesTr/case_3.npz
2022-11-24 14:18:25.173 | INFO     | scripts.preprocess:check_case:264 - Checking /data.local.3/USERNAME/ML/data/Task000D3_Example/raw_cropped/imagesTr/case_4.npz
2022-11-24 14:18:25.636 | INFO     | scripts.preprocess:check_case:264 - Checking /data.local.3/USERNAME/ML/data/Task000D3_Example/raw_cropped/imagesTr/case_5.npz
2022-11-24 14:18:26.099 | INFO     | scripts.preprocess:check_case:264 - Checking /data.local.3/USERNAME/ML/data/Task000D3_Example/raw_cropped/imagesTr/case_6.npz
2022-11-24 14:18:26.562 | INFO     | scripts.preprocess:check_case:264 - Checking /data.local.3/USERNAME/ML/data/Task000D3_Example/raw_cropped/imagesTr/case_7.npz
2022-11-24 14:18:27.025 | INFO     | scripts.preprocess:check_case:264 - Checking /data.local.3/USERNAME/ML/data/Task000D3_Example/raw_cropped/imagesTr/case_8.npz
2022-11-24 14:18:27.488 | INFO     | scripts.preprocess:check_case:264 - Checking /data.local.3/USERNAME/ML/data/Task000D3_Example/raw_cropped/imagesTr/case_9.npz
2022-11-24 14:18:27.951 | INFO     | scripts.preprocess:run_check:242 - Checked 10 cases in /data.local.3/USERNAME/ML/data/Task000D3_Example/raw_cropped/imagesTr
2022-11-24 14:18:27.951 | INFO     | scripts.preprocess:run_cropping_and_convert:100 - Crop check successful: Loading check completed
2022-11-24 14:18:27.955 | INFO     | nndet.planning.properties.instance:analyze_instances_per_case:157 - Processing instance properties of case case_0
Traceback (most recent call last):
  File "/home/USERNAME/miniconda3/bin/nndet_prep", line 33, in <module>
    sys.exit(load_entry_point('nndet', 'console_scripts', 'nndet_prep')())
  File "/home/USERNAME/git/nnDetection/nndet/utils/check.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "/home/USERNAME/git/nnDetection/scripts/preprocess.py", line 406, in main
    run(OmegaConf.to_container(cfg, resolve=True),
  File "/home/USERNAME/git/nnDetection/scripts/preprocess.py", line 325, in run
    run_dataset_analysis(cropped_output_dir=Path(cfg["host"]["cropped_output_dir"]),
  File "/home/USERNAME/git/nnDetection/scripts/preprocess.py", line 129, in run_dataset_analysis
    _ = analyzer.analyze_dataset(properties)
  File "/home/USERNAME/git/nnDetection/nndet/planning/analyzer.py", line 80, in analyze_dataset
    props.update(property_fn(self))
  File "/home/USERNAME/git/nnDetection/nndet/planning/properties/instance.py", line 46, in analyze_instances
    props_per_case = run_analyze_instances(analyzer, all_classes)
  File "/home/USERNAME/git/nnDetection/nndet/planning/properties/instance.py", line 77, in run_analyze_instances
    props = [analyze_instances_per_case(*args) for args in zip(
  File "/home/USERNAME/git/nnDetection/nndet/planning/properties/instance.py", line 77, in <listcomp>
    props = [analyze_instances_per_case(*args) for args in zip(
  File "/home/USERNAME/git/nnDetection/nndet/planning/properties/instance.py", line 159, in analyze_instances_per_case
    props["num_instances"] = count_instances(props, all_classes)
  File "/home/USERNAME/git/nnDetection/nndet/planning/properties/instance.py", line 180, in count_instances
    instance_classes = list(map(int, props["instances"].values()))
KeyError: 'instances'

```

**Comment by xaratustrah** [comment] 2022-11-24 14:08
Your idea about pahts: I put changed the `data` and `model` directories to be in `/home` not like previous times, where they where on `/data.local.3/` which is another SSD hard disk drive mounted there on the node. While `\home` is on a separate SSD hard drive of its own.
 
Now `nndet_prep 000D3 -np 0 -npp 0 --full_check` finishes successfully.

So in order to exclude that that specific SSD hard disk has a problem, I put `data` and `model` directories to be on yet another hard disk of my little monster, on `/data.local.4/`. Here again crashes with the errors above.

I have otherwise no other IO problems, and filesystems seem to be the same, and there is enough space for everyone `findmnt -lo source,target,fstype,label,options,used,avail -t ext4 | sort` says:

```
/dev/sda2 /             ext4         rw,relatime,errors=remount-ro  75.2G 471.4G
/dev/sda3 /home         ext4         rw,relatime                    51.4G 180.2G
/dev/sdb1 /data.local.1 ext4         rw,relatime                   624.5G 209.9G
/dev/sdc  /data.local.2 ext4         rw,relatime                      87M 834.3G
/dev/sdd  /data.local.3 ext4         rw,relatime                     6.9G 827.5G
/dev/sde  /data.local.4 ext4         rw,relatime                     2.9G 831.5G
SOURCE    TARGET        FSTYPE LABEL OPTIONS                         USED  AVAIL
```

Does the code require to work under `/home`? I wonder how else this can be explained.

**Comment by mibaumgartner** [comment] 2022-11-24 14:22
Ah, thanks for the update! It is not required that the data is located in /home but the folder names/mount points are not allowed to have '.' inside them. I'll add an additional check for this and extend the readme. I may need to update the path handling to something more robust in the future 😅

**Comment by xaratustrah** [comment] 2022-11-24 14:26
OMG, I was thinking of everything except that! I think in the Readme you had already mentioned that no "." are allowed in the file names, but I never thought about folder names. Yes, indeed it would be nice to fix it, in Linux systems, dots are everywhere. 

Thanks anyways!

**Closed as completed** 2022-11-24 15:01 UTC
