### ISSUE TITLE
[Question] docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].

### ISSUE THREAD

**Issue by aldemirfilho** [MIC-DKFZ/nnDetection#77] opened 2022-05-03 22:31 UTC
### :question: Question

Hi, can you help me with this error I have been getting? Initially it worked correctly and the other day when running I had this error.

Thanks!

**Comment by mibaumgartner** [comment] 2022-05-04 10:56
Hi @aldemirfilho ,

sounds like this is either caused by a mismatched driver (there is a minimal driver version for the docker image) or something strange is going on. Did you try restarting your pc?

**Comment by mibaumgartner** [comment] 2022-05-30 08:23
Since there was no update for some time,  I'll close the Issue for now but if anything else comes up please reopen (if the same) or open a new one.

**Closed by mibaumgartner** 2022-05-30 08:23 UTC
